# Generated by Django 4.2.16 on 2024-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_for_times',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='times',
            field=models.IntegerField(),
        ),
    ]
