# Generated by Django 4.2.16 on 2024-11-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_time_for_times_alter_task_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_for_times',
            new_name='minutes_for_times',
        ),
    ]
